name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API image
        run: |
          docker build -f sdv-api/Dockerfile -t your-dockerhub-username/sdv-api:latest .
          docker push your-dockerhub-username/sdv-api:latest

      - name: Build and push Web image
        run: |
          docker build -f sdv-web/Dockerfile -t your-dockerhub-username/sdv-web:latest .
          docker push your-dockerhub-username/sdv-web:latest
